In [1]:
import pandas as pd
import numpy as np
from sklearn import preprocessing
import matplotlib.pyplot as plt 
plt.rc("font", size=14)
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
import seaborn as sns
sns.set(style="white")
sns.set(style="whitegrid", color_codes=True)

In [2]:
#Import csv file of dataset and convert to DF
nba_df = pd.read_csv("nba.csv")

In [3]:
#Import csv file of dataset and convert to DF
nba_scaled_df = pd.read_csv("nba_scaled.csv")

In [4]:
#Import csv file of dataset and convert to DF
nba_scaled_larger_df = pd.read_csv("nba_larger_scaled.csv")

In [5]:
nba_df

,Unnamed: 0,WL_x,AST_x,AST_y,BLK_x,BLK_y,DREB_x,DREB_y,FG3_PCT_x,FG3_PCT_y,...,FT_PCT_x,FT_PCT_y,FTA_x,FTA_y,OREB_x,OREB_y,STL_x,STL_y,TOV_x,TOV_y
0,0,1,27.1,25.0,4.5,4.0,35.7,33.2,0.364,0.332,...,0.769,0.789,20.3,23.2,9.8,12.0,8.8,8.3,14.9,14.1
1,1,1,27.1,27.9,4.5,4.9,35.7,34.3,0.364,0.352,...,0.769,0.754,20.3,20.4,9.8,11.0,8.8,7.6,14.9,12.7
2,2,1,27.1,23.7,4.5,4.5,35.7,33.4,0.364,0.344,...,0.769,0.768,20.3,23.3,9.8,9.6,8.8,7.2,14.9,14.1
3,3,0,27.1,26.0,4.5,6.5,35.7,35.0,0.364,0.353,...,0.769,0.734,20.3,23.1,9.8,14.1,8.8,9.8,14.9,13.2
4,4,0,27.1,25.0,4.5,5.0,35.7,34.1,0.364,0.342,...,0.769,0.783,20.3,21.7,9.8,9.0,8.8,6.4,14.9,13.1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
14750,14750,1,22.1,19.0,5.7,5.1,30.5,30.0,0.332,0.353,...,0.730,0.762,22.8,23.1,11.3,11.8,6.5,6.0,15.7,14.9
14751,14751,0,22.1,21.0,5.7,5.1,30.5,30.5,0.332,0.359,...,0.730,0.772,22.8,30.6,11.3,10.8,6.5,8.3,15.7,13.9
14752,14752,0,22.1,21.1,5.7,4.9,30.5,32.5,0.332,0.341,...,0.730,0.765,22.8,24.2,11.3,11.9,6.5,7.5,15.7,13.4
14753,14753,0,22.1,18.8,5.7,4.9,30.5,30.4,0.332,0.337,...,0.730,0.733,22.8,26.9,11.3,13.0,6.5,7.9,15.7,15.2
14754,14754,0,22.1,20.4,5.7,4.3,30.5,29.1,0.332,0.354,...,0.730,0.790,22.8,24.8,11.3,11.1,6.5,6.4,15.7,12.3

In [6]:
nba_scaled_df

,Unnamed: 0,WL_x,AST_x,BLK_x,DREB_x,FG3_PCT_x,FG_PCT_x,FT_PCT_x,FTA_x,OREB_x,STL_x,TOV_x
0,0,1,0.978166,1.088889,1.095385,1.040462,1.065611,1.009211,1.083333,1.038462,0.900000,0.965517
1,1,0,0.826568,1.088889,0.997199,0.989011,1.004264,0.997399,1.152709,1.102041,0.818182,0.939597
2,2,0,0.933333,0.980000,1.020057,0.962567,1.028384,0.967213,1.193878,1.186813,0.972973,1.021898
3,3,0,0.957265,1.225000,1.053254,1.028571,1.021692,0.994812,1.103774,1.161290,1.074627,1.120000
4,4,0,0.797153,1.000000,1.056380,0.986301,1.006410,1.036486,1.093458,1.000000,0.837209,1.052632
...,...,...,...,...,...,...,...,...,...,...,...,...
14750,14750,1,1.163158,1.117647,1.016667,0.940510,1.013363,0.958005,0.987013,0.957627,1.083333,1.053691
14751,14751,0,1.052381,1.117647,1.000000,0.924791,0.972222,0.945596,0.745098,1.046296,0.783133,1.129496
14752,14752,0,1.047393,1.163265,0.938462,0.973607,0.995624,0.954248,0.942149,0.949580,0.866667,1.171642
14753,14753,0,1.175532,1.163265,1.003289,0.985163,0.970149,0.995907,0.847584,0.869231,0.822785,1.032895
14754,14754,0,1.083333,1.325581,1.048110,0.937853,0.986985,0.924051,0.919355,1.018018,1.015625,1.276423

In [7]:
nba_scaled_larger_df

,Unnamed: 0,WL_x,AST_x,BLK_x,DREB_x,FG3_PCT_x,FG_PCT_x,FT_PCT_x,FTA_x,OREB_x,STL_x,TOV_x
0,0,0,1.198113,0.933333,0.958599,0.937008,0.997821,0.988665,0.890756,1.207921,1.106667,1.000000
1,1,0,1.289340,1.272727,0.977273,1.000000,1.011038,1.035620,0.834646,1.089286,1.152778,0.945578
2,2,0,1.316062,0.888889,0.964744,1.053097,1.022321,1.132756,0.844622,1.042735,1.383333,0.879747
3,3,0,1.104348,0.933333,0.955556,1.037791,0.984946,1.149341,0.743860,0.924242,1.202899,0.965278
4,4,1,1.062762,1.098039,0.993399,1.022923,0.978632,1.030184,0.913793,1.042735,1.012195,0.908497
...,...,...,...,...,...,...,...,...,...,...,...,...
23721,23721,0,1.033582,1.066667,1.035398,0.997347,0.964948,0.977584,1.082051,0.761905,1.012346,1.111111
23722,23722,1,1.144628,0.923077,1.060423,1.071225,1.035398,1.034256,0.901709,0.833333,1.108108,1.006711
23723,23723,1,1.033582,1.142857,0.994334,1.016216,0.983193,0.992415,1.205714,0.833333,1.223881,0.993377
23724,23724,0,1.086275,1.043478,0.928571,0.966581,0.960986,1.032895,0.985981,0.776699,1.012346,1.086957
23725,23725,0,1.033582,0.905660,0.988732,0.959184,0.947368,0.976368,0.937778,0.898876,1.223881,1.111111

In [8]:
#Create X (features) and y (target) to feed model
#Create X (features) and y (target) to feed model 
cols=["AST_x", "AST_y", "BLK_x", "BLK_y", "DREB_x", "DREB_y", "FG3_PCT_x", "FG3_PCT_y", "FG_PCT_x", "FG_PCT_y",
      "FT_PCT_x", "FT_PCT_y", "FTA_x", "FTA_y", "OREB_x", "OREB_y", "STL_x", "STL_y", "TOV_x", "TOV_y"]
X=nba_df[cols]
y=nba_df['WL_x']

In [9]:
#same as before, but now use the ratio columns instead of both x and y
cols2=["AST_x", "BLK_x", "DREB_x", "FG3_PCT_x", "FG_PCT_x", "FT_PCT_x", "FTA_x", "OREB_x", "STL_x", "TOV_x"]
X=nba_scaled_df[cols2]
y=nba_scaled_df['WL_x']

In [10]:
#same as before, but now use the ratio columns instead of both x and y
cols2=["AST_x", "BLK_x", "DREB_x", "FG3_PCT_x", "FG_PCT_x", "FT_PCT_x", "FTA_x", "OREB_x", "STL_x", "TOV_x"]
X=nba_scaled_larger_df[cols2]
y=nba_scaled_larger_df['WL_x']

In [11]:
#Check if the p values for these features are below .05 (if they're any good at predicting the outcome of the game)
#Consider removing any columns that don't yield a p value below .05. Can skip if our values are all high, just won't yield as good of a model
import statsmodels.api as sm
logit_model=sm.Logit(y,X)
result=logit_model.fit()
print(result.summary2())

Optimization terminated successfully.
         Current function value: 0.628405
         Iterations 5
                         Results: Logit
=================================================================
Model:              Logit            Pseudo R-squared: 0.069
Dependent Variable: WL_x             AIC:              29839.0702
Date:               2022-05-04 21:31 BIC:              29919.8134
No. Observations:   23726            Log-Likelihood:   -14910.
Df Model:           9                LL-Null:          -16016.
Df Residuals:       23716            LLR p-value:      0.0000
Converged:          1.0000           Scale:            1.0000
No. Iterations:     5.0000
------------------------------------------------------------------
              Coef.   Std.Err.     z      P>|z|    [0.025   0.975]
------------------------------------------------------------------
AST_x         0.5839    0.1484    3.9344  0.0001   0.2930   0.8747
BLK_x         0.5489    0.0609    9.0127  0.0000   0.4295   0.6682
DREB_x        3.0359    0.2421   12.5403  0.0000   2.5614   3.5104
FG3_PCT_x     1.1932    0.2356    5.0649  0.0000   0.7315   1.6550
FG_PCT_x      2.4140    0.3965    6.0889  0.0000   1.6370   3.1911
FT_PCT_x     -4.2255    0.2315  -18.2494  0.0000  -4.6793  -3.7717
FTA_x         0.8280    0.1195    6.9314  0.0000   0.5939   1.0622
OREB_x       -1.0182    0.0951  -10.7024  0.0000  -1.2046  -0.8317
STL_x         0.8344    0.0979    8.5208  0.0000   0.6425   1.0263
TOV_x        -4.6030    0.1379  -33.3821  0.0000  -4.8733  -4.3328
=================================================================

In [12]:
#Check if the p values for these features are below .05 (if they're any good at predicting the outcome of the game)
#Consider removing any columns that don't yield a p value below .05. Can skip if our values are all high, just won't yield as good of a model
import statsmodels.api as sm
logit_model=sm.Logit(y,X)
result=logit_model.fit()
print(result.summary2())

Optimization terminated successfully.
         Current function value: 0.628405
         Iterations 5
                         Results: Logit
=================================================================
Model:              Logit            Pseudo R-squared: 0.069
Dependent Variable: WL_x             AIC:              29839.0702
Date:               2022-05-04 21:31 BIC:              29919.8134
No. Observations:   23726            Log-Likelihood:   -14910.
Df Model:           9                LL-Null:          -16016.
Df Residuals:       23716            LLR p-value:      0.0000
Converged:          1.0000           Scale:            1.0000
No. Iterations:     5.0000
------------------------------------------------------------------
              Coef.   Std.Err.     z      P>|z|    [0.025   0.975]
------------------------------------------------------------------
AST_x         0.5839    0.1484    3.9344  0.0001   0.2930   0.8747
BLK_x         0.5489    0.0609    9.0127  0.0000   0.4295   0.6682
DREB_x        3.0359    0.2421   12.5403  0.0000   2.5614   3.5104
FG3_PCT_x     1.1932    0.2356    5.0649  0.0000   0.7315   1.6550
FG_PCT_x      2.4140    0.3965    6.0889  0.0000   1.6370   3.1911
FT_PCT_x     -4.2255    0.2315  -18.2494  0.0000  -4.6793  -3.7717
FTA_x         0.8280    0.1195    6.9314  0.0000   0.5939   1.0622
OREB_x       -1.0182    0.0951  -10.7024  0.0000  -1.2046  -0.8317
STL_x         0.8344    0.0979    8.5208  0.0000   0.6425   1.0263
TOV_x        -4.6030    0.1379  -33.3821  0.0000  -4.8733  -4.3328
=================================================================

In [13]:
# #Interesting, noted that all p values are below zero now with the ratio'd df 
# #same as before, but now use the ratio columns instead of both x and y
# #I want to try with just the ones that had huge z scores (basically doing feature selection to choose)
# cols3=["BLK_x", "DREB_x", "FG3_PCT_x", "FT_PCT_x", "OREB_x", "TOV_x"]
# X=nba_scaled_df[cols3]
# y=nba_scaled_df['WL_x']

In [14]:
# #Create X (features) and y (target) to feed model
# #Removed AST_x, and BLK_x because those had above .05 p values. 
# cols=["AST_y", "BLK_y", "DREB_x", "DREB_y", "FG3_PCT_x", "FG3_PCT_y", "FG_PCT_x", "FG_PCT_y",
#       "FT_PCT_x", "FT_PCT_y", "FTA_x", "FTA_y", "OREB_x", "OREB_y", "STL_x", "STL_y", "TOV_x", "TOV_y"]
# X=nba_df[cols]
# y=nba_df['WL_x']

In [15]:
#Check if the p values for these features are below .05 (if they're any good at predicting the outcome of the game)
#Consider removing any columns that don't yield a p value below .05. Can skip if our values are all high, just won't yield as good of a model
import statsmodels.api as sm
logit_model=sm.Logit(y,X)
result=logit_model.fit()
print(result.summary2())

Optimization terminated successfully.
         Current function value: 0.628405
         Iterations 5
                         Results: Logit
=================================================================
Model:              Logit            Pseudo R-squared: 0.069
Dependent Variable: WL_x             AIC:              29839.0702
Date:               2022-05-04 21:31 BIC:              29919.8134
No. Observations:   23726            Log-Likelihood:   -14910.
Df Model:           9                LL-Null:          -16016.
Df Residuals:       23716            LLR p-value:      0.0000
Converged:          1.0000           Scale:            1.0000
No. Iterations:     5.0000
------------------------------------------------------------------
              Coef.   Std.Err.     z      P>|z|    [0.025   0.975]
------------------------------------------------------------------
AST_x         0.5839    0.1484    3.9344  0.0001   0.2930   0.8747
BLK_x         0.5489    0.0609    9.0127  0.0000   0.4295   0.6682
DREB_x        3.0359    0.2421   12.5403  0.0000   2.5614   3.5104
FG3_PCT_x     1.1932    0.2356    5.0649  0.0000   0.7315   1.6550
FG_PCT_x      2.4140    0.3965    6.0889  0.0000   1.6370   3.1911
FT_PCT_x     -4.2255    0.2315  -18.2494  0.0000  -4.6793  -3.7717
FTA_x         0.8280    0.1195    6.9314  0.0000   0.5939   1.0622
OREB_x       -1.0182    0.0951  -10.7024  0.0000  -1.2046  -0.8317
STL_x         0.8344    0.0979    8.5208  0.0000   0.6425   1.0263
TOV_x        -4.6030    0.1379  -33.3821  0.0000  -4.8733  -4.3328
=================================================================

In [16]:
#Once we have good independent variables, use split the X and Y into training and testing sets so we can see how well 
#the model predicts the outcome of a game
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [17]:
#Check how good our results are using the Logistic Regression model from sklearn
y_pred = logreg.predict(X_test)
print(logreg.score(X_test, y_test))
#print('Accuracy of logistic regression classifier on test set: ' + logreg.score(X_test, y_test))

0.6621241921888171

In [18]:
#Once we have good independent variables, use split the X and Y into training and testing sets so we can see how well 
#the model predicts the outcome of a game
#make sure to run the box that creates x and y from the scaled df before this box
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [19]:
#Check how good our results are using the Logistic Regression model from sklearn using new scaled ratios
y_pred = logreg.predict(X_test)
print(logreg.score(X_test, y_test))
#print('Accuracy of logistic regression classifier on test set: ' + logreg.score(X_test, y_test))

0.6621241921888171

In [20]:
X_test

,AST_x,BLK_x,DREB_x,FG3_PCT_x,FG_PCT_x,FT_PCT_x,FTA_x,OREB_x,STL_x,TOV_x
17693,0.955102,1.022222,0.934718,0.941504,1.000000,1.092414,1.058824,0.943396,0.898876,0.925926
438,1.092233,0.940000,0.962145,1.162577,1.024609,1.056376,0.823741,0.908397,0.976190,0.867089
7068,0.837838,1.307692,0.976821,0.980716,1.019438,0.890863,1.206612,1.217391,0.971831,1.259259
11069,1.100000,0.980769,0.981538,0.951351,0.962578,1.013004,0.863799,1.260417,1.106061,0.942446
22855,1.112033,0.888889,1.034268,1.002717,1.015625,0.933742,0.981221,1.127660,0.906977,1.121212
...,...,...,...,...,...,...,...,...,...,...
21485,1.094017,1.255814,1.034091,0.979412,1.051454,0.942049,0.920949,1.009901,1.153846,1.105634
9195,1.112745,0.854545,1.071429,1.112045,1.063457,1.014589,1.109649,1.049505,0.962025,1.248000
5523,1.046632,0.907407,1.020690,0.973262,1.022321,1.068917,1.122530,1.039216,1.082192,1.021739
10340,0.915179,0.865385,0.935976,0.916010,0.940206,1.008333,0.902256,1.239583,1.000000,1.079137
13111,1.009009,0.903846,0.906907,0.859155,0.958515,1.072254,0.892473,1.034783,1.214286,0.986667

In [21]:
#We can also look at a confusion matrix for the testing set to see where we're incurring errors
from sklearn.metrics import confusion_matrix
y_pred = logreg.predict(X_test)
confusion_matrix = confusion_matrix(y_test, y_pred)
print(confusion_matrix)

[[3437  779]
 [1626 1276]]

In [22]:
from sklearn.metrics import precision_recall_fscore_support
y_pred = logreg.predict(X_test)
metrics = precision_recall_fscore_support(y_test, y_pred, average='binary')
print("precision on test set: " + str(metrics[0]))
print("recall on test set: " + str(metrics[1]))
print("F1 on test set: " + str(metrics[2]))

precision on test set: 0.6209245742092457
recall on test set: 0.43969676085458304
F1 on test set: 0.514827516643131

In [23]:
nba_df["WL_x"].value_counts()

0    8583
1    6172
Name: WL_x, dtype: int64

In [24]:
#Once we have good independent variables, use split the X and Y into training and testing sets so we can see how well 
#the model predicts the outcome of a game
#make sure to run the box that creates x and y from the scaled df before this box
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [25]:
#Check how good our results are using the Logistic Regression model from sklearn using new scaled ratios
#less features performs worse, stick with using all
y_pred = logreg.predict(X_test)
print(logreg.score(X_test, y_test))
#print('Accuracy of logistic regression classifier on test set: ' + logreg.score(X_test, y_test))

0.6621241921888171

In [26]:
#larger dataframe logreg fit
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_train, y_train)

LogisticRegression(max_iter=1000)

In [27]:
#Check how good our results are using the Logistic Regression model from sklearn using new scaled ratios
y_pred = logreg.predict(X_test)
print(logreg.score(X_test, y_test))

0.6621241921888171

In [28]:
from sklearn.metrics import precision_recall_fscore_support
y_pred = logreg.predict(X_test)
metrics = precision_recall_fscore_support(y_test, y_pred, average='binary')
print("precision on test set: " + str(metrics[0]))
print("recall on test set: " + str(metrics[1]))
print("F1 on test set: " + str(metrics[2]))

precision on test set: 0.6209245742092457
recall on test set: 0.43969676085458304
F1 on test set: 0.514827516643131

In [29]:
#Import csv file of dataset and convert to DF
nba_scaled_larger_df = pd.read_csv("nba_larger_scaled.csv")
#same as before, but now use the ratio columns instead of both x and y
cols2=["AST_x", "BLK_x", "DREB_x", "FG3_PCT_x", "FG_PCT_x", "FT_PCT_x", "FTA_x", "OREB_x", "STL_x", "TOV_x"]
X_r=nba_scaled_larger_df[cols2]
y_r=nba_scaled_larger_df['WL_x']

In [30]:
#larger dataframe logreg fit
from sklearn.linear_model import LogisticRegression
from sklearn import metrics
#X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state=0)
logreg = LogisticRegression(max_iter=1000)
logreg.fit(X_r, y_r)

LogisticRegression(max_iter=1000)

In [31]:
#Import csv file of dataset and convert to DF
playoff_df = pd.read_csv("playoffs_2015.csv")

In [32]:
playoff_df

,Unnamed: 0,WL_x,AST_x,BLK_x,DREB_x,FG3_PCT_x,FG_PCT_x,FT_PCT_x,FTA_x,OREB_x,STL_x,TOV_x,PLUS_MINUS_x
0,0,1,0.785467,0.639344,0.936464,0.870192,0.944559,0.980341,0.995413,1.060000,0.797619,0.894737,4.0
1,1,1,0.785467,0.639344,0.936464,0.870192,0.944559,0.980341,0.995413,1.060000,0.797619,0.894737,15.0
2,2,0,0.785467,0.639344,0.936464,0.870192,0.944559,0.980341,0.995413,1.060000,0.797619,0.894737,-33.0
3,3,0,0.785467,0.639344,0.936464,0.870192,0.944559,0.980341,0.995413,1.060000,0.797619,0.894737,-15.0
4,4,1,1.213904,0.709091,1.021084,0.978378,1.019956,0.962677,0.812734,1.039216,0.858974,1.038168,26.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
81,81,0,0.960870,0.627119,0.952247,0.985673,0.932773,1.015345,0.884921,0.702290,0.918919,0.805031,-38.0
82,82,0,0.854626,0.948718,1.000000,0.953039,0.954348,0.893048,1.175115,1.179245,1.044776,0.992647,-17.0
83,83,0,0.854626,0.948718,1.000000,0.953039,0.954348,0.893048,1.175115,1.179245,1.044776,0.992647,-5.0
84,84,0,0.844898,0.728814,0.884058,0.882667,0.909091,0.975093,1.210784,1.191489,1.060241,1.015267,-26.0
85,85,0,0.844898,0.728814,0.884058,0.882667,0.909091,0.975093,1.210784,1.191489,1.060241,1.015267,-32.0

In [33]:
#same as before, but now use the ratio columns instead of both x and y
cols2=["AST_x", "BLK_x", "DREB_x", "FG3_PCT_x", "FG_PCT_x", "FT_PCT_x", "FTA_x", "OREB_x", "STL_x", "TOV_x"]
X_p=playoff_df[cols2]
y_p=playoff_df['WL_x']

In [34]:
print(logreg.score(X_p, y_p))

0.6162790697674418

In [35]:
y_pred = logreg.predict(X_p)
from sklearn.metrics import confusion_matrix
confusion_matrix = confusion_matrix(y_p, y_pred)
print(confusion_matrix)

[[44 14]
 [19  9]]

In [36]:
celts_nets_df = pd.read_csv("celtics_nets.csv")

In [37]:
celts_nets_df

,Unnamed: 0,AST_x,BLK_x,DREB_x,FG3_PCT_x,FG_PCT_x,FT_PCT_x,FTA_x,OREB_x,STL_x,TOV_x,YEAR
0,0,0.980237,1.054545,1.041056,0.98615,0.981053,1.013665,0.963134,1.019417,1.014085,0.964539,2021-22

In [38]:
cols2=["AST_x", "BLK_x", "DREB_x", "FG3_PCT_x", "FG_PCT_x", "FT_PCT_x", "FTA_x", "OREB_x", "STL_x", "TOV_x"]
X=celts_nets_df[cols2]

In [39]:
game_pred = logreg.predict_proba(X)

In [40]:
print(game_pred)

[[0.57006999 0.42993001]]

In [41]:
print(X)

      AST_x     BLK_x    DREB_x  FG3_PCT_x  FG_PCT_x  FT_PCT_x     FTA_x  \
0  0.980237  1.054545  1.041056    0.98615  0.981053  1.013665  0.963134

     OREB_x     STL_x     TOV_x
0  1.019417  1.014085  0.964539

In [45]:
print(logreg.predict_proba(playoff_df[["AST_x", "BLK_x", "DREB_x", "FG3_PCT_x", "FG_PCT_x", "FT_PCT_x", "FTA_x", "OREB_x", "STL_x", "TOV_x"]]))

[[0.83173928 0.16826072]
 [0.83173928 0.16826072]
 [0.83173928 0.16826072]
 [0.83173928 0.16826072]
 [0.70018374 0.29981626]
 [0.70018374 0.29981626]
 [0.70018374 0.29981626]
 [0.58238319 0.41761681]
 [0.58238319 0.41761681]
 [0.54403998 0.45596002]
 [0.54403998 0.45596002]
 [0.29823391 0.70176609]
 [0.29823391 0.70176609]
 [0.29823391 0.70176609]
 [0.42264385 0.57735615]
 [0.42264385 0.57735615]
 [0.42264385 0.57735615]
 [0.27188272 0.72811728]
 [0.27188272 0.72811728]
 [0.24524151 0.75475849]
 [0.24524151 0.75475849]
 [0.75070428 0.24929572]
 [0.75070428 0.24929572]
 [0.75070428 0.24929572]
 [0.75070428 0.24929572]
 [0.73516947 0.26483053]
 [0.73516947 0.26483053]
 [0.73516947 0.26483053]
 [0.4255159  0.5744841 ]
 [0.4255159  0.5744841 ]
 [0.49494523 0.50505477]
 [0.49494523 0.50505477]
 [0.49494523 0.50505477]
 [0.5321795  0.4678205 ]
 [0.5321795  0.4678205 ]
 [0.5321795  0.4678205 ]
 [0.50891334 0.49108666]
 [0.50891334 0.49108666]
 [0.50891334 0.49108666]
 [0.67303302 0.32696698]
 [0.67303302 0.32696698]
 [0.67303302 0.32696698]
 [0.67303302 0.32696698]
 [0.65443422 0.34556578]
 [0.65443422 0.34556578]
 [0.65443422 0.34556578]
 [0.47467473 0.52532527]
 [0.47467473 0.52532527]
 [0.47467473 0.52532527]
 [0.22825717 0.77174283]
 [0.22825717 0.77174283]
 [0.85010779 0.14989221]
 [0.85010779 0.14989221]
 [0.85010779 0.14989221]
 [0.76284757 0.23715243]
 [0.76284757 0.23715243]
 [0.76284757 0.23715243]
 [0.59845839 0.40154161]
 [0.59845839 0.40154161]
 [0.59827833 0.40172167]
 [0.59827833 0.40172167]
 [0.59827833 0.40172167]
 [0.56441814 0.43558186]
 [0.56441814 0.43558186]
 [0.56441814 0.43558186]
 [0.56441814 0.43558186]
 [0.70887372 0.29112628]
 [0.70887372 0.29112628]
 [0.70887372 0.29112628]
 [0.70887372 0.29112628]
 [0.41499295 0.58500705]
 [0.41499295 0.58500705]
 [0.41499295 0.58500705]
 [0.84791468 0.15208532]
 [0.84791468 0.15208532]
 [0.84791468 0.15208532]
 [0.60370514 0.39629486]
 [0.60370514 0.39629486]
 [0.60370514 0.39629486]
 [0.76227602 0.23772398]
 [0.76227602 0.23772398]
 [0.76227602 0.23772398]
 [0.66625746 0.33374254]
 [0.66625746 0.33374254]
 [0.86762576 0.13237424]
 [0.86762576 0.13237424]]

In [173]:
#Profibility of our playoff season predicitions. Uses plus/minus set by NBA to determine how much money was won or lost
def moneylineProfits(df, logreg, wagerpct, starting_sum, limit):
    predictions = logreg.predict_proba(playoff_df[["AST_x", "BLK_x", "DREB_x", "FG3_PCT_x", "FG_PCT_x", "FT_PCT_x", "FTA_x", "OREB_x", "STL_x", "TOV_x"]])
    df_odds = df[['PLUS_MINUS_x', 'WL_x']]
    for index, row in df_odds.iterrows():
        pred = predictions[index]
        if pred[0] > limit:
            wager = wagerpct * starting_sum
            starting_sum = starting_sum - wager
            if row['WL_x'] == 1:
                starting_sum = starting_sum + (wager * 2)
        elif pred[0] < 1 - limit:
            wager = wagerpct * starting_sum
            starting_sum = starting_sum - wager
            if row['WL_x'] == 0:
                starting_sum = starting_sum + (wager * 2)

    return starting_sum

In [182]:
moneylineProfits(playoff_df, logreg, 0.01, 1000, 0.8)

922.5601547164815